alter table blog change blog_id blog_id int unsigned not null auto_increment;
alter table tag change column tags tag_name varchar(20);
alter table tag change column tags tag_name varchar(20);
alter table tag change tag_name tags varchar(20);
alter table tag add constraint unique(tag_name);
alter table comments add column post_id int unsigned ,add foreign key (post_id) references post(post_id) on delete cascade;
alter table comments drop column post_id;
alter table comments drop foreign key comments_ibfk_1;
alter table comments drop foreign key post_id;
alter table comments drop column post_id;
alter table blog add column created_date date;
alter table blog modify blog_url varchar(20) not null unique;
show create table tagging_post;
show create table tag;
show create table comments;
show create table post;
show create table category;
show create table blog;